---
- name: Descargar imagen Docker
  hosts: localhost
  

  tasks:
  - name: Descargar Tomcat 
    community.docker.docker_image:
      name: tomcat
      source: pull

  - name: Etiquetar de nuevo el tomcat
    community.docker.docker_image:
      name: tomcat
      repository: mi-tomcat
      source: local