---
- name: Hardening - Activar Microsoft Defender
  ansible.windows.win_command: powershell.exe -Command "Set-MpPreference -DisableRealtimeMonitoring $false; Set-MpPreference -DisableBehaviorMonitoring $false"

- name: Hardening - Aplicar política estricta de Firewall
  # El módulo correcto para perfiles globales es ansible.windows.win_firewall
  ansible.windows.win_firewall:
    state: enabled
    profiles:
      - Domain
      - Private
      - Public
    inbound_action: block
    outbound_action: allow

- name: Hardening - Deshabilitar Telnet si está presente
  # El módulo win_service es correcto, pero asegúrate de usar el FQCN
  ansible.windows.win_service:
    name: TlntSvr
    state: stopped
    start_mode: disabled
  ignore_errors: yes
