---
- name: Chequeo básico de localhost RHEL8
  hosts: localhost
  gather_facts: yes
  become: true

  vars:
    servicios_importantes:
      - sshd.servcie
      - firewalld.service
      - chronyd.service

  tasks:
    - name: Verificar conectividad a localhost
      ansible.builtin.ping:

    - name: Mostrar algunos facts del sistema
      ansible.builtin.debug:
        msg:
          - "Hostname: {{ ansible_hostname }}"
          - "SO: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Kernel: {{ ansible_kernel }}"

    - name: Comprobar uso de disco en /
      ansible.builtin.command: df -h /
      register: uso_disco

    - name: Mostrar uso de disco en /
      ansible.builtin.debug:
        var: uso_disco.stdout_lines

    - name: Verificar estado de servicios importantes
      ansible.builtin.service_facts:
        
    - name: Verificar estado de servicios importantes
      ansible.builtin.debug:
         var: ansible_facts.services
        msg: >-
           Servicio {{ item }}:
           {{
             'state=' ~ ansible_facts.services[item + '.service'].state ~
              ', status=' ~ ansible_facts.services[item + '.service'].status
              if (ansible_facts.services is defined and
                 (item + '.service') in ansible_facts.services)
              else 'no existe o no está registrado en systemd'
            }}
      loop: "{{ servicios_importantes }}"

...
