---
- name: Laboratorio de Active Directory Grupos y ambitos
  hosts: windows
  gather_facts: no
  vars:
    target_ou: "OU=IT,OU=Departamentos,DC=vzpaD,DC=info"
    target_group: "APPS_IT"


  tasks:
    
    - name: Crear un grupo para la OU de Ventas
      microsoft.ad.group:
        name: Impresora_ventas
        category: security
        scope: domainlocal
        path: OU=groups,DC=vzpaD,DC=info
        state: present

    - name: Crear un grupo para la OU de Ventas
      microsoft.ad.group:
        name: APPS_ventas
        category: security
        scope: global
        path: OU=groups,DC=vzpaD,DC=info
        state: present

    - name: Crear un grupo para la OU de RRHH
      microsoft.ad.group:
        name: Impresora_RRHH
        category: security
        scope: domainlocal
        path: OU=groups,DC=vzpaD,DC=info
        state: present

    - name: Crear un grupo para la OU de RRHH
      microsoft.ad.group:
        name: APPS_RHH
        category: security
        scope: global
        path: OU=groups,DC=vzpaD,DC=info
        state: present

    - name: Crear un grupo para la OU de IT 
      microsoft.ad.group:
        name: Impresora_IT
        category: security
        scope: domainlocal
        path: OU=groups,DC=vzpaD,DC=info
        state: present

    - name: Crear un grupo para la OU de IT
      microsoft.ad.group:
        name: APPS_IT
        category: security
        scope: global
        path: OU=groups,DC=vzpaD,DC=info
        state: present

    - name: Crear un grupo para la OU de IT
      microsoft.ad.group:
        name: EmpleadosInternos_VZPADINFO
        category: security
        scope: universal
        path: OU=groups,DC=vzpaD,DC=info
        state: present

    - name: Crear grupo de distribución para IT
      ansible.windows.win_powershell:
        script: |
          Import-Module ActiveDirectory
    
          if (-not (Get-ADGroup -Filter "Name -eq 'IT-Mail'" -ErrorAction SilentlyContinue)) {
            New-ADGroup `
              -Name "IT-Mail" `
              -SamAccountName "IT-Mail" `
              -GroupScope Universal `
              -GroupCategory Distribution `
              -Path "OU=groups,DC=vzpaD,DC=info"
          }


    - name: Obtener usuarios de una OU de IT
      ansible.windows.win_powershell:
        script: |
          Import-Module ActiveDirectory
          Get-ADUser -SearchBase "{{ target_ou }}" -Filter * |
          Select-Object -ExpandProperty SamAccountName
      register: ou_users
      
    - name: Agregar usuarios de la OU IT al grupo
      ansible.windows.win_powershell:
        script: |
          Import-Module ActiveDirectory
    
          $group = "IT-Mail"
          $ou = "OU=groups,DC=vzpaD,DC=info""
    
          $users = Get-ADUser -SearchBase $ou -Filter *
    
          foreach ($user in $users) {
            if (-not (Get-ADGroupMember -Identity $group -Recursive |
                      Where-Object {$_.DistinguishedName -eq $user.DistinguishedName})) {
    
              Add-ADGroupMember -Identity $group -Members $user
            }
          }



