---
- name: Crear OUs por departamento y usuarios en Active Directory
  hosts: windows
  gather_facts: false
  vars:
    domain: "vzpaD.info"
    domain_dn: "DC=vzpaD,DC=info"
    # OU raíz para departamentos
    base_ou: "OU=Departamentos,{{ domain_dn }}"
    default_password: "P@ssw0rd123!"
    ad_users:
      - username: jperez
        firstname: Juan
        lastname: Pérez
        email: jperez@{{domain}}
        department: IT
        title: Desarrollador
      - username: mgarcia
        firstname: María
        lastname: García
        email: mgarcia@{{domain}}
        department: RecursosHumanos
        title: Gerente de RRHH
      - username: clopez
        firstname: Carlos
        lastname: López
        email: clopez@{{domain}}
        department: Ventas
        title: Ejecutivo de Ventas
  tasks:
    # 1️⃣ Crear OU raíz "Departamentos"
    - name: Crear OU raíz Departamentos si no existe
      microsoft.ad.ou:
        name: "Departamentos"
        path: "{{ domain_dn }}"
        state: present
    
    # 2️⃣ Crear OUs por departamento (únicos)
    - name: Crear OUs por departamento
      microsoft.ad.ou:
        name: "{{ item }}"
        path: "{{ base_ou }}"
        state: present
      loop: "{{ ad_users | map(attribute='department') | unique | list }}"
    
    # 3️⃣ Crear usuarios en Active Directory
    - name: Crear usuarios en Active Directory
      microsoft.ad.user:
        name: "{{ item.firstname }} {{ item.lastname }}"
        sam_account_name: "{{ item.username }}"
        upn: "{{ item.username }}@vzpaD.info"
        
        firstname: "{{ item.firstname }}"
        lastname: "{{ item.lastname }}"
        email: "{{ item.email }}"
        
        password: "{{ default_password }}"
        enabled: true
        password_expired: true
        
        path: "OU={{ item.department }},{{ base_ou }}"
        
        attributes:
          set:
            department: "{{ item.department }}"
            title: "{{ item.title }}"
        
        state: present
      loop: "{{ ad_users }}"

    - name: Ensure OU is present & protected
      microsoft.ad.ou:
        name: groups
        path: DC=vzpaD,DC=info
        state: present
        protect_from_deletion: true


    - name: Create a group in a custom path
      microsoft.ad.group:
        name: EmployerInternal_VZPADINFO
        scope: global
        path: OU=groups,DC=vzpaD,DC=info
        state: present

    - name: Agregar usuarios de Departamentos al grupo EmployerInternal_VZPADINFO
      microsoft.ad.group:
        name: "EmployerInternal_VZPADINFO"
        members:
          add: "{{ ad_users | map(attribute='username') | list }}"
        state: present
