- block:
    - name: Crear carpeta de logs si no existe
      ansible.windows.win_shell: |
        if (-Not (Test-Path "{{ log_path }}")) {
          New-Item -ItemType Directory -Path "{{ log_path }}"
        }

    - name: Actualizar aplicaciones definidas en vars.yaml
      ansible.windows.win_shell: |
        foreach ($app in {{ winget_apps | to_json }}) {
          try {
            winget upgrade --id $app --silent --accept-source-agreements --accept-package-agreements
            Add-Content -Path "{{ report_file }}" -Value "Aplicación actualizada: $app"
          } catch {
            Add-Content -Path "{{ report_file }}" -Value "Error al actualizar: $app"
          }
        }
