---
- name: Compliance - Ejecutar script de validación
  ansible.windows.win_shell: |
    powershell.exe -ExecutionPolicy Bypass -File "{{ playbook_dir }}/../scripts/setup_winrm.ps1"
  register: compliance_check
  ignore_errors: yes

- name: Crear directorio de logs si no existe
  ansible.windows.win_file:
    path: "{{ log_path }}"
    state: directory

- name: Guardar resultado de compliance en log
  ansible.windows.win_copy:
    content: "{{ compliance_check.stdout | default('No output') }}"
    dest: "{{ log_path }}compliance.log"

- name: Mostrar resultado en consola AWX
  debug:
    msg: "{{ compliance_check.stdout | default('No output') }}"
