---
- name: IronClad Compliance Check
  hosts: windows
  become: false
  gather_facts: no

  vars_files:
    - ../vars/main.yml

  tasks:
    - name: Copiar script de validación al host remoto
      ansible.windows.win_copy:
        src: "{{ playbook_dir }}/../scripts/setup_winrm.ps1"
        dest: "C:\\Scripts\\setup_winrm.ps1"

    - name: Ejecutar script de validación de cumplimiento
      ansible.windows.win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File "C:\\Scripts\\setup_winrm.ps1"
      register: compliance_check
      ignore_errors: yes

    - name: Crear directorio de logs si no existe
      ansible.windows.win_file:
        path: "{{ log_path }}"
        state: directory

    - name: Guardar resultado en compliance.log
      ansible.windows.win_copy:
        content: "{{ compliance_check.stdout | default('No output') }}"
        dest: "{{ log_path }}compliance.log"

    - name: Mostrar resultado en consola AWX
      debug:
        msg: "{{ compliance_check.stdout | default('No output') }}"
