---
- name: Obtener datos de disco vía PowerShell
  ansible.windows.win_powershell:
    script: |
          $drive = Get-PSDrive C
          $ansible_view = @{
            total = $drive.Used + $drive.Free
            free  = $drive.Free
          }
          $ansible_view
      register: info_disco
- name: Mostrar resultado formateado
  ansible.builtin.debug:
    msg:
          - "Disco: C:"
          - "Total: {{ info_disco.output[0].total | filesizeformat }}"
          - "Libre: {{ info_disco.output[0].free | filesizeformat }}"
